import test from 'node:test';
import assert from 'node:assert/strict';
import { mockChrome } from './mock-chrome.js';
const mock=mockChrome();
globalThis.chrome=mock.chrome;
const menus=[];let clicked;
chrome.runtime.onInstalled={addListener(){}};
chrome.runtime.onStartup={addListener(){}};
chrome.tabs.onAttached={addListener(){}};
chrome.tabs.onDetached={addListener(){}};
chrome.tabGroups.onUpdated={addListener(){}};
chrome.runtime.onConnect={addListener(){}};
chrome.contextMenus={async removeAll(){menus.length=0;},create(item,callback){menus.push(item);callback();},onClicked:{addListener(fn){clicked=fn;}}};
mock.data.local.arcSidebarModel={favorites:[],spaces:[{id:'work',title:'Work',children:[]}]};
await import('../src/background/context-menu.js');
const settle=async predicate=>{for(let n=0;n<100;n++){if(predicate())return;await new Promise(r=>setTimeout(r,5));}assert.fail('Context menu operation did not finish');};
test('Favorites precedes Spaces, pins current live page and links, and works without Spaces',async()=>{
 await settle(()=>menus.length===3);
 assert.deepEqual(menus.map(m=>m.id),['arc-sidebar-pin-root','arc-sidebar-pin-favorites','arc-sidebar-pin-space:work']);
 clicked({menuItemId:'arc-sidebar-pin-favorites',pageUrl:'https://a.test'},{id:10,url:'https://a.test',title:'Current page'});
 await settle(()=>mock.data.local.arcSidebarModel.favorites.length===1 && Object.keys(mock.data.session.arcSidebarBindings||{}).length===1);
 const first=mock.data.local.arcSidebarModel.favorites[0];
 assert.equal(first.title,'Current page');assert.equal(mock.data.session.arcSidebarBindings[first.id],10);
 clicked({menuItemId:'arc-sidebar-pin-favorites',linkUrl:'https://link.test'},{id:10,url:'https://a.test'});
 await settle(()=>mock.data.local.arcSidebarModel.favorites.length===2);
 assert.equal(mock.data.local.arcSidebarModel.favorites[1].url,'https://link.test');
 assert.equal(Object.keys(mock.data.session.arcSidebarBindings).length,1);
 await chrome.storage.local.set({arcSidebarModel:{favorites:[],spaces:[]}});
 await settle(()=>menus.length===2);
 assert.equal(menus[0].enabled,true);
 clicked({menuItemId:'arc-sidebar-pin-favorites',linkUrl:'https://no-spaces.test'},{});
 await settle(()=>mock.data.local.arcSidebarModel.favorites.length===1);
 assert.equal(mock.data.local.arcSidebarModel.stats.favorites,1);
});

test('fresh/reset startup initializes Favorites and My Space and context menu can pin immediately',async()=>{
 await chrome.storage.local.clear();
 clicked({menuItemId:'arc-sidebar-pin-favorites',pageUrl:'https://a.test'},{id:10,url:'https://a.test',title:'First Favorite'});
 await settle(()=>mock.data.local.arcSidebarModel?.favorites?.length===1);
 assert.equal(mock.data.local.arcSidebarModel.spaces.length,1);
 assert.equal(mock.data.local.arcSidebarModel.spaces[0].emoji,'🚀');
 const favorite=mock.data.local.arcSidebarModel.favorites[0];
 assert.equal(favorite.title,'First Favorite');
 assert.equal(mock.data.session.arcSidebarBindings[favorite.id],10);
 await settle(()=>menus.some(menu=>menu.id==='arc-sidebar-pin-favorites'));
});
