import test from 'node:test';
import assert from 'node:assert/strict';
import {mockChrome} from './mock-chrome.js';
const mock=mockChrome();globalThis.chrome=mock.chrome;
const {ensureEmptySidebar}=await import('../src/background/empty-sidebar.js');
test('fresh and reset models contain Favorites and a selected rocket My Space; imports replace the defaults',async()=>{
 await ensureEmptySidebar();
 assert.deepEqual(mock.data.local.arcSidebarModel.favorites,[]);
 assert.deepEqual(mock.data.local.arcSidebarModel.spaces,[{id:'__my_space__',title:'My Space',emoji:'🚀',children:[]}]);
 assert.equal(mock.data.local.arcSidebarState.currentSpaceId,'__my_space__');
 const imported={version:2,favorites:[{id:'fav',type:'tab',url:'https://a.test'}],spaces:[]};
 await chrome.storage.local.set({arcSidebarModel:imported});
 await Promise.all([ensureEmptySidebar(),ensureEmptySidebar()]);
 assert.deepEqual(mock.data.local.arcSidebarModel,imported);
 await chrome.storage.local.clear();
 await ensureEmptySidebar();
 assert.deepEqual(mock.data.local.arcSidebarModel.favorites,[]);
 assert.deepEqual(mock.data.local.arcSidebarModel.spaces,[{id:'__my_space__',title:'My Space',emoji:'🚀',children:[]}]);
 assert.equal(mock.data.local.arcSidebarState.currentSpaceId,'__my_space__');
});
